name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

jobs:
  hadolint-pr:
    runs-on: ubuntu-latest
    name: PR - Hadolint
    steps:
      - uses: actions/checkout@v3
        # Ignores do not work: https://github.com/reviewdog/action-hadolint/issues/35 is resolved
      - uses: reviewdog/action-hadolint@v1
        with:
          exclude: |
            packaging/testing/smoke/packages/Dockerfile.*

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: cmake/sanitizers-cmake lib plugins tests

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  coding-style-pr:
    runs-on: ubuntu-latest
    name: PR - Coding Style checks
    steps:
      - uses: actions/checkout@v3

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # version: '16'
          style: file
          ignore: lib/

      # We can explicitly fail but by default the action does not so add this to fail the workflow if we want
      - if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # run: exit 1
